trigger:
  - main 

pool:
  name: Default  

steps:
  # Step 1: Checkout the code from GitHub
  - task: Checkout@1
    displayName: "Checkout Code from GitHub"
    inputs:
      clean: true

  # Step 2: Install .NET SDK (optional if installed locally)
  - task: UseDotNet@2
    displayName: "Install .NET Core SDK"
    inputs:
      packageType: sdk
      version: '8.x'

  # Step 3: Restore project dependencies
  - script: dotnet restore
    displayName: "Restore Dependencies"

  # Step 4: Build the project
  - script: dotnet build --configuration Release
    displayName: "Build Project"

  # Step 5: Publish build artifacts
  - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
    displayName: "Publish Artifacts"

  # Step 6: Upload artifacts
  - task: PublishBuildArtifacts@1
    displayName: "Upload Artifacts"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'AzureDevOpsQuizApp'
