trigger:
  - main 

pool:
  name: Default  

steps:
  # Step 1: Checkout the code from your GitHub repository
  - task: Checkout@1
    displayName: "Checkout Code from GitHub"
    inputs:
      clean: true

  # Step 2: Install .NET SDK (if required for your environment)
  - task: UseDotNet@2
    displayName: "Install .NET Core SDK"
    inputs:
      packageType: sdk
      version: '8.x'  
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Step 3: Restore project dependencies
  - script: dotnet restore
    displayName: "Restore Project Dependencies"
    workingDirectory: .

  # Step 4: Build the project
  - script: dotnet build --configuration Release
    displayName: "Build Project"
    workingDirectory: .

  # Step 6: Publish build artifacts
  - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
    displayName: "Publish Build Artifacts"
    workingDirectory: .

  # Step 7: Save the artifacts
  - task: PublishBuildArtifacts@1
    displayName: "Upload Artifacts"
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'AzureDevOpsQuizApp'
      publishLocation: 'Container'
